apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_DB: d2ViYXBw
  POSTGRES_USER: d2ViYXBwX3VzZXI=
  POSTGRES_PASSWORD: TWF5dXJlc2hAMTIz
  DATABASE_URL: cG9zdGdyZXNxbDovL3dlYmFwcF91c2VyOk1heXVyZXNoQDEyM0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvd2ViYXBw

