apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "mayu007",
          "password": "Mayuresh@123",
          "email": "mayuresh.satao@gmail.com",
          "auth": "bWF5dXJlc2guc2F0YW9AZ21haWwuY29tOk1heXVyZXNoQDEyMw=="
        }
      }
    }