-- V1.0__init.sql
CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.instructor (
    id SERIAL PRIMARY KEY,
    instructor_id UUID NOT NULL,
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api.course (
    id SERIAL PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    semesterTerm VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255),
    creditHours INTEGER NOT NULL CHECK (creditHours BETWEEN 0 AND 4),
    semesterYear INTEGER NOT NULL CHECK (semesterYear BETWEEN 2000 AND 2050),
    date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_user_id INTEGER NOT NULL,
    instructorId INTEGER NOT NULL,
    CONSTRAINT fk_instructor FOREIGN KEY (instructorId) REFERENCES api.instructor(id)
);

CREATE TABLE IF NOT EXISTS api.user (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    account_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    account_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api.trace (
    trace_id UUID NOT NULL,
    user_id UUID NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bucket_path VARCHAR(255) NOT NULL
);
