apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
data:
  flyway.conf: |
    flyway.url=jdbc:postgresql://${POSTGRES_HOST}:5432/webapp
    flyway.schemas=webapp
    flyway.defaultSchema=webapp
    flyway.user=${POSTGRES_USER}
    flyway.password=${POSTGRES_PASSWORD}
    flyway.locations=filesystem:/flyway/sql
    flyway.baselineOnMigrate=true
    flyway.validateOnMigrate=true
